#!/usr/bin/env node
/**
 * Klipr icon codegen — `npm run icons`
 *
 * Reads the curated brand icons in `Functional Icons/<Name>/<file>.svg`
 * (Streamline Core outline style: viewBox 0 0 14 14, stroke #35055A,
 * round caps/joins, no stroke-width) and emits ONE typed React module:
 * `components/icons/index.tsx`.
 *
 * Transformations per KLIPR-BUILD-PLAN.md §1.5:
 *  - strip <g clip-path> wrappers and <defs> (clip rects are full-bleed)
 *  - stroke="#35055A" → stroke="currentColor"
 *  - kebab-case attributes → camelCase (JSX)
 *  - add vectorEffect="non-scaling-stroke" so icons stay hairline-crisp
 *    at 16/20/24px instead of scaling the stroke.
 *
 * To add an icon: copy the chosen SVG from `Klipr/Icons/` into a new
 * `Functional Icons/<Name>/` folder, add the name mapping below, re-run.
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(root, "Functional Icons");
const OUT = join(root, "components", "icons", "index.tsx");

/** Folder name → exported component name. */
const NAME_MAP = {
  Add: "IconAdd",
  Analytics: "IconChart",
  ArrowRight: "IconArrowRight",
  Bolt: "IconBolt",
  Campaign: "IconCampaign",
  Check: "IconCheck",
  CheckCircle: "IconCheckCircle",
  ChevronLeft: "IconChevronLeft",
  ChevronRight: "IconChevronRight",
  Clock: "IconClock",
  Dashboard: "IconHome",
  Earnings: "IconWallet",
  Filter: "IconFilter",
  Fire: "IconFire",
  Flag: "IconFlag",
  Graph: "IconGraph",
  Leaderboard: "IconTrophy",
  Link: "IconLink",
  Megaphone: "IconMegaphone",
  Notifications: "IconBell",
  Play: "IconPlay",
  Profile: "IconProfile",
  Reject: "IconX",
  Search: "IconSearch",
  Send: "IconSend",
  Settings: "IconGear",
  Shield: "IconShield",
  Submit: "IconUpload",
  UserMultiple: "IconUsers",
  Verified: "IconVerified",
  Warning: "IconWarning",
  bKash: "IconBkash",
};

const kebabToCamel = (s) => s.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

function extractBody(svg) {
  // inner markup of <svg>…</svg>
  let body = svg.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "");
  // strip defs (clipPath rects are full-bleed 14×14 — safe to drop)
  body = body.replace(/<defs>[\s\S]*?<\/defs>/g, "");
  // unwrap <g clip-path="…"> … </g>
  body = body.replace(/<g clip-path="[^"]*">/g, "").replace(/<\/g>/g, "");
  return body.trim();
}

function toJsx(body) {
  return body
    .replace(/stroke="#35055A"/gi, 'stroke="currentColor"')
    .replace(/fill="#35055A"/gi, 'fill="currentColor"')
    // kebab-case presentation attributes → camelCase
    .replace(/([a-z]+(?:-[a-z]+)+)=/g, (m, attr) => `${kebabToCamel(attr)}=`)
    // every drawn element keeps a crisp device-px stroke
    .replace(/<(path|rect|circle|ellipse|line|polyline|polygon)\b/g, '<$1 vectorEffect="non-scaling-stroke"')
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean)
    .map((l) => `      ${l}`)
    .join("\n");
}

const dirs = readdirSync(SRC, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort();

const missing = dirs.filter((d) => !NAME_MAP[d]);
if (missing.length) {
  console.error(`No NAME_MAP entry for: ${missing.join(", ")} — add one in scripts/gen-icons.mjs`);
  process.exit(1);
}

const components = [];
for (const dir of dirs) {
  const files = readdirSync(join(SRC, dir)).filter((f) => f.endsWith(".svg"));
  if (files.length !== 1) {
    console.error(`Expected exactly one .svg in "Functional Icons/${dir}", found ${files.length}`);
    process.exit(1);
  }
  const svg = readFileSync(join(SRC, dir, files[0]), "utf8");
  components.push({ name: NAME_MAP[dir], source: `${dir}/${files[0]}`, jsx: toJsx(extractBody(svg)) });
}

const header = `/* AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
 * Source: the curated brand icon set in "Functional Icons/" (Streamline Core
 * outline style, viewBox 0 0 14 14). Re-run \`npm run icons\` after changing
 * any source SVG. See KLIPR-BUILD-PLAN.md §1.5.
 */

export interface IconProps {
  /** Rendered square size in px. */
  size?: number;
  /** Device-px stroke width (non-scaling). 1.25 = the Klipr hairline. */
  strokeWidth?: number;
  className?: string;
}
`;

const bodyOut = components
  .map(
    (c) => `
/** ${c.source} */
export function ${c.name}({ size = 16, strokeWidth = 1.25, className }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 14 14"
      fill="none"
      strokeWidth={strokeWidth}
      className={className}
      aria-hidden="true"
    >
${c.jsx}
    </svg>
  );
}`,
  )
  .join("\n");

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, header + bodyOut + "\n");
console.log(`Wrote ${components.length} icons → components/icons/index.tsx`);
for (const c of components) console.log(`  ${c.name}  ←  ${c.source}`);
